### ISSUE TITLE
Failed to run sonar gate check on an aggregated project, in which there is some module without sonar report

### ISSUE THREAD

**Issue by Neola** [r0bb3n/sonar-quality-gate-maven-plugin#55]
we have some aggregated projects, which have many modules, and there is no sonar report for some of modules. 
when we run "sonar:sonar sonar-quality-gate:check" , it will failed with 404 error, failed to find the project key. 
error like below,
[ERROR] Failed to execute goal io.github.r0bb3n:sonar-quality-gate-maven-plugin:1.0.2:check (default-cli) on project api: Bad status code '404' returned from xxxx 

as I know sonar:sonar also scan all the modules, but not failed, if sonar-quality-gate:check also can only check the modules with sonar report intelligently.

**Comment by Neola** [comment]
sonar:sonar generate report based on the top pom, but sonar-quality-gate-maven-plugin:check scan each module to check, which is not our want.

**Comment by r0bb3n** [comment]
Hi @Neola ,
thanks for your message, I will have a look into it.
Regards,
r0bb3n

**Comment by r0bb3n** [comment]
@Neola 
please check this [SNAPSHOT](https://oss.sonatype.org/#nexus-search;gav~io.github.r0bb3n~sonar-quality-gate-maven-plugin~1-SNAPSHOT~~), release is coming soon.
